name: CI

on: 
  push: 
    branches:
      - "**"
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request: 
    branches:
      - "**"
    paths-ignore:
      - "README.md"
      - "LICENSE"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint